name: myapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_polyline_points: ^0.1.0
  permission: ^0.1.7
  flutter_map: ^0.9.0
  flutter_map_tappable_polyline: ^0.3.2
  google_map_polyline: ^0.2.0+1
  firebase_storage: ^3.1.5
  firebase_messaging: ^6.0.13
  flutter_spinkit: "^4.1.2"
  url_launcher: ^5.4.5
  shared_preferences: ^0.5.6+3
  background_fetch: ^0.5.5
  google_maps_flutter: ^0.5.26
  cloud_firestore: ^0.13.4+2
  firebase_core: ^0.4.4+3
  firebase_database: ^3.1.3
  custom_radio_button: ^0.0.3
  sms: ^0.2.4
  permission_handler: ^5.0.0+hotfix.3
  contacts_service: ^0.3.10
  firebase_auth: ^0.15.5+3
  geolocator: ^5.3.1
  location: ^3.0.2
  geocoder: ^0.2.1
  humanitarian_icons: ^0.1.0
  provider: ^4.0.4
  http: ^0.12.0+4
  image_picker: ^0.6.4
  sqflite: ^1.3.0
  path: ^1.6.4

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_size.jpg"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "assets/logo_size.jpg"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Caladea-Bold
      fonts:
        - asset: fonts/Caladea-Bold.ttf
       
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
